@ReqeustTest_HostAdress = http://localhost:80/api/auth

### 회원가입
POST {{ReqeustTest_HostAdress}}/register
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "user1234"
}

### 로그인
POST {{ReqeustTest_HostAdress}}/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

### 로그아웃
@auth_token = WDPDR9IgmJ2Wd92ps6S1AA
POST {{ReqeustTest_HostAdress}}/logout
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "token": "{{auth_token}}" 
}

### 비밀번호 변경
POST {{ReqeustTest_HostAdress}}/change-password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userId": 1,
  "currentPassword": "password123",
  "newPassword": "newpassword456"
}