@ReqeustTest_HostAdress = http://localhost:80/api/deck

### 덱 목록 요청
POST {{ReqeustTest_HostAdress}}/list
Content-Type: application/json

{
  "userId" : "20"
}

### 덱 업데이트
POST {{ReqeustTest_HostAdress}}/update
Content-Type: application/json
{
  "userId" : "20",
  "deckIndex" : "1",
  "characterIds" : [ "12", "13", "0" ]
}