@ReqeustTest_HostAdress = http://localhost:5000/api/deck

### 덱 목록 요청
POST {{ReqeustTest_HostAdress}}/list
Content-Type: application/json

{
  "userId" : "2"
}

### 덱 업데이트
POST {{ReqeustTest_HostAdress}}/update
Content-Type: application/json
{
  "userId" : "2",
  "deckIndex" : "1",
  "characterIds" : [ "0", "1", "0" ]
}