@ReqeustTest_HostAdress = http://localhost:5000/api/gacha

### 뽑기 리스트 요청
POST {{ReqeustTest_HostAdress}}/list
Content-Type: application/json

{
  
}

### 뽑기 요청
POST {{ReqeustTest_HostAdress}}/draw
Content-Type: application/json

{
  "userId": "2"
  "gachaCode": "test_cacha",
}