@ReqeustTest_HostAdress = http://localhost:80/api/user
@auth_token = 1111

### 유저 정보 요청
POST {{ReqeustTest_HostAdress}}/info
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userId" : "2"
}